name = "keyring-be"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionDurableObject"

[[migrations]]
tag = "v1"
new_classes = [ "SessionDurableObject" ]


[[d1_databases]]
binding = "DB"
database_name = "keyring-db"
database_id = "dc4cfae2-3ab9-4def-8f03-1dda78e3abe2" # Placeholder

[vars]
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://keyring.biyeon.store"
